BEGIN TRAN
GO

IF NOT EXISTS (SELECT * FROM [sys].[sysobjects] WHERE [id] = OBJECT_ID('[dbo].[champions]'))
BEGIN
	CREATE TABLE [dbo].[champions]
	(
		[id] BIGINT PRIMARY KEY IDENTITY(1,1),
		[code] BIGINT NOT NULL,
		[key] VARCHAR(45) NOT NULL,
		[originalName] VARCHAR(45) NOT NULL,
		[name] VARCHAR(45) NOT NULL,
		[updated_date] DATETIME NOT NULL DEFAULT(SYSDATETIME()),
		[is_deleted] BIT DEFAULT(0)
	)
END


IF EXISTS (SELECT * FROM [sys].[sysobjects] WHERE [id] = OBJECT_ID('[dbo].[champions]'))
BEGIN
	INSERT INTO [dbo].[champions] ([code], [key], [originalName], [name])
	SELECT * FROM
	(
		VALUES
		(266, 'Aatrox', 'Aatrox', 'Атрокс'),
		(103, 'Ahri', 'Ahri', 'Ари'),
		(84, 'Akali', 'Akali', 'Акали'),
		(166, 'Akshan', 'Akshan', 'Акшан'),
		(12, 'Alistar', 'Alistar', 'Алистар'),
		(32, 'Amumu', 'Amumu', 'Амуму'),
		(34, 'Anivia', 'Anivia', 'Анивия'),
		(1, 'Annie', 'Annie', 'Энни'),
		(523, 'Aphelios', 'Aphelios', 'Афелий'),
		(22, 'Ashe', 'Ashe', 'Эш'),
		(136, 'AurelionSol', 'Aurelion Sol', 'Аурелион Сол'),
		(268, 'Azir', 'Azir', 'Азир'),
		(432, 'Bard', 'Bard', 'Бард'),
		(200, 'Belveth', 'Bel`Veth', 'БелВет'),
		(53, 'Blitzcrank', 'Blitzcrank', 'Блицкранк'),
		(63, 'Brand', 'Brand', 'Бренд'),
		(201, 'Braum', 'Braum', 'Браум'),
		(233, 'Briar', 'Briar', 'Брайер'),
		(51, 'Caitlyn', 'Caitlyn', 'Кейтлин'),
		(164, 'Camille', 'Camille', 'Камилла'),
		(69, 'Cassiopeia', 'Cassiopeia', 'Кассиопея'),
		(31, 'Chogath', 'Cho`Gath', 'Чо`Гат'),
		(42, 'Corki', 'Corki', 'Корки'),
		(122, 'Darius', 'Darius', 'Дариус'),
		(131, 'Diana', 'Diana', 'Диана'),
		(119, 'Draven', 'Draven', 'Дрейвен'),
		(36, 'DrMundo', 'Dr. Mundo', 'Доктор Мундо'),
		(245, 'Ekko', 'Ekko', 'Экко'),
		(60, 'Elise', 'Elise', 'Элиза'),
		(28, 'Evelynn', 'Evelynn', 'Эвелин'),
		(81, 'Ezreal', 'Ezreal', 'Эзреаль'),
		(9, 'Fiddlesticks', 'Fiddlesticks', 'Фиддлстикс'),
		(114, 'Fiora', 'Fiora', 'Фиора'),
		(105, 'Fizz', 'Fizz', 'Физз'),
		(3, 'Galio', 'Galio', 'Галио'),
		(41, 'Gangplank', 'Gangplank', 'Гангпланк'),
		(86, 'Garen', 'Garen', 'Гарен'),
		(150, 'Gnar', 'Gnar', 'Гнар'),
		(79, 'Gragas', 'Gragas', 'Грагас'),
		(104, 'Graves', 'Graves', 'Грейвс'),
		(887, 'Gwen', 'Gwen', 'Гвен'),
		(120, 'Hecarim', 'Hecarim', 'Гекарим'),
		(74, 'Heimerdinger', 'Heimerdinger', 'Хаймердингер'),
		(420, 'Illaoi', 'Illaoi', 'Иллаой'),
		(39, 'Irelia', 'Irelia', 'Ирелия'),
		(427, 'Ivern', 'Ivern', 'Иверн'),
		(40, 'Janna', 'Janna', 'Джанна'),
		(59, 'JarvanIV', 'Jarvan IV', 'Джарван IV'),
		(24, 'Jax', 'Jax', 'Джакс'),
		(126, 'Jayce', 'Jayce', 'Джейс'),
		(202, 'Jhin', 'Jhin', 'Джин'),
		(222, 'Jinx', 'Jinx', 'Джинкс'),
		(145, 'Kaisa', 'Kai`Sa', 'Кай`Са'),
		(429, 'Kalista', 'Kalista', 'Калиста'),
		(43, 'Karma', 'Karma', 'Карма'),
		(30, 'Karthus', 'Karthus', 'Картус'),
		(38, 'Kassadin', 'Kassadin', 'Кассадин'),
		(55, 'Katarina', 'Katarina', 'Катарина'),
		(10, 'Kayle', 'Kayle', 'Кейл'),
		(141, 'Kayn', 'Kayn', 'Каин'),
		(85, 'Kennen', 'Kennen', 'Кеннен'),
		(121, 'Khazix', 'Kha`Zix', 'Казикс'),
		(203, 'Kindred', 'Kindred', 'Киндред'),
		(240, 'Kled', 'Kled', 'Клед'),
		(96, 'KogMaw', 'Kog`Maw', 'Ког`Мао'),
		(897, 'KSante', 'K`Sante', 'К`Санте'),
		(7, 'Leblanc', 'LeBlanc', 'Леблан'),
		(64, 'LeeSin', 'Lee Sin', 'Ли Син'),
		(89, 'Leona', 'Leona', 'Леона'),
		(876, 'Lillia', 'Lillia', 'Лилия'),
		(127, 'Lissandra', 'Lissandra', 'Лиссандра'),
		(236, 'Lucian', 'Lucian', 'Люциан'),
		(117, 'Lulu', 'Lulu', 'Лулу'),
		(99, 'Lux', 'Lux', 'Люкс'),
		(54, 'Malphite', 'Malphite', 'Мальфит'),
		(90, 'Malzahar', 'Malzahar', 'Мальзахар'),
		(57, 'Maokai', 'Maokai', 'Маокай'),
		(11, 'MasterYi', 'Master Yi', 'Мастер Йи'),
		(21, 'MissFortune', 'Miss Fortune', 'Мисс Фортуна'),
		(62, 'MonkeyKing', 'Wukong', 'Вуконг'),
		(82, 'Mordekaiser', 'Mordekaiser', 'Мордекайзер'),
		(25, 'Morgana', 'Morgana', 'Моргана'),
		(267, 'Nami', 'Nami', 'Нами'),
		(75, 'Nasus', 'Nasus', 'Насус'),
		(111, 'Nautilus', 'Nautilus', 'Наутилус'),
		(518, 'Neeko', 'Neeko', 'Нико'),
		(76, 'Nidalee', 'Nidalee', 'Нидали'),
		(56, 'Nocturne', 'Nocturne', 'Ноктюрн'),
		(20, 'Nunu', 'Nunu', 'Нуну'),
		(2, 'Olaf', 'Olaf', 'Олаф'),
		(61, 'Orianna', 'Orianna', 'Орианна'),
		(516, 'Ornn', 'Ornn', 'Орнн'),
		(80, 'Pantheon', 'Pantheon', 'Пантеон'),
		(78, 'Poppy', 'Poppy', 'Поппи'),
		(555, 'Pyke', 'Pyke', 'Пайк'),
		(246, 'Qiyana', 'Qiyana', 'Киана'),
		(133, 'Quinn', 'Quinn', 'Квинн'),
		(497, 'Rakan', 'Rakan', 'Рейкан'),
		(33, 'Rammus', 'Rammus', 'Раммус'),
		(421, 'RekSai', 'Rek`Sai', 'Рек`Сай'),
		(58, 'Renekton', 'Renekton', 'Ренектон'),
		(107, 'Rengar', 'Rengar', 'Ренгар'),
		(92, 'Riven', 'Riven', 'Ривен'),
		(68, 'Rumble', 'Rumble', 'Рамбл'),
		(13, 'Ryze', 'Ryze', 'Райз'),
		(360, 'Samira', 'Samira', 'Самира'),
		(113, 'Sejuani', 'Sejuani', 'Седжуани'),
		(235, 'Senna', 'Senna', 'Сенна'),
		(147, 'Seraphine', 'Seraphine', 'Серафина'),
		(875, 'Sett', 'Sett', 'Сетт'),
		(35, 'Shaco', 'Shaco', 'Шако'),
		(98, 'Shen', 'Shen', 'Шен'),
		(102, 'Shyvana', 'Shyvana', 'Шивана'),
		(27, 'Singed', 'Singed', 'Синджед'),
		(14, 'Sion', 'Sion', 'Сион'),
		(15, 'Sivir', 'Sivir', 'Сивир'),
		(72, 'Skarner', 'Skarner', 'Скарнер'),
		(37, 'Sona', 'Sona', 'Сона'),
		(16, 'Soraka', 'Soraka', 'Сорака'),
		(50, 'Swain', 'Swain', 'Свейн'),
		(517, 'Sylas', 'Sylas', 'Сайлас'),
		(134, 'Syndra', 'Syndra', 'Синдра'),
		(223, 'TahmKench', 'Tahm Kench', 'Там Кенч'),
		(163, 'Taliyah', 'Taliyah', 'Талия'),
		(91, 'Talon', 'Talon', 'Талон'),
		(44, 'Taric', 'Taric', 'Тарик'),
		(17, 'Teemo', 'Teemo', 'Тимо'),
		(412, 'Thresh', 'Thresh', 'Треш'),
		(18, 'Tristana', 'Tristana', 'Тристана'),
		(48, 'Trundle', 'Trundle', 'Трандл'),
		(23, 'Tryndamere', 'Tryndamere', 'Триндамир'),
		(4, 'TwistedFate', 'Twisted Fate', 'Твистед Фейт'),
		(29, 'Twitch', 'Twitch', 'Твич'),
		(77, 'Udyr', 'Udyr', 'Удир'),
		(6, 'Urgot', 'Urgot', 'Ургот'),
		(110, 'Varus', 'Varus', 'Варус'),
		(67, 'Vayne', 'Vayne', 'Вейн'),
		(45, 'Veigar', 'Veigar', 'Вейгар'),
		(161, 'Velkoz', 'Vel`Koz', 'Вел`Коз'),
		(254, 'Vi', 'Vi', 'Вай'),
		(112, 'Viktor', 'Viktor', 'Виктор'),
		(8, 'Vladimir', 'Vladimir', 'Владимир'),
		(106, 'Volibear', 'Volibear', 'Волибир'),
		(19, 'Warwick', 'Warwick', 'Варвик'),
		(498, 'Xayah', 'Xayah', 'Шая'),
		(101, 'Xerath', 'Xerath', 'Зерат'),
		(5, 'XinZhao', 'Xin Zhao', 'Ксин Жао'),
		(157, 'Yasuo', 'Yasuo', 'Ясуо'),
		(777, 'Yone', 'Yone', 'Ёне'),
		(83, 'Yorick', 'Yorick', 'Йорик'),
		(350, 'Yuumi', 'Yuumi', 'Юми'),
		(154, 'Zac', 'Zac', 'Зак'),
		(238, 'Zed', 'Zed', 'Зед'),
		(115, 'Ziggs', 'Ziggs', 'Зиггс'),
		(26, 'Zilean', 'Zilean', 'Зилеан'),
		(142, 'Zoe', 'Zoe', 'Зои'),
		(143, 'Zyra', 'Zyra', 'Зайра')
	) AS [List] ([code], [key], [originalName], [name])
	WHERE NOT EXISTS (SELECT 1 FROM [dbo].[champions] WHERE [code] = [List].[code])
END;

GO
COMMIT TRAN